# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  core: openapi/core.yaml
  admin: openapi/admin.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index2.html
  hideLogo: true
  theme:
    menu:
      backgroundColor: '#ffffff'
    colors:
      primary:
        main: "#f4a261"
    typography:
      fontFamily: fantasy
generateCodeSamples:
  languages:
    - lang: curl
    - lang: Node.js
    - lang: C#
    - lang: Python
    - lang: Java
    - lang: Go
    - lang: Ruby
