# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
  core: openapi/silohub-core.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
generateCodeSamples:
  languages:
    - lang: curl
    - lang: Node.js
    - lang: C#
    - lang: Python
    - lang: Java
    - lang: Go
    - lang: Ruby
