### Site metadata

title: SILOHUB API Pages
description: Una prueba más y van

### Build settings

url: https://api.silohub.ag
baseurl: /

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - README.md
  - sample.png