openapi: 3.0.3
info:
  title: "SILOHUB Retailer API"
  description: |
    Esta API es el core de negocio del retailer para SILOHUB
  version: "0.0"
  x-group: "API"
  x-client-id: "api-client-retailer"
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  contact:
    name: SILOHUB Support
    email: support@silohub.ag
    url: 'https://silohub.atlassian.net/servicedesk/customer/portals'
externalDocs:
  description: Confluence
  url: 'https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs'
servers:
  - url: 'https://{apiServer}'
    variables:
      apiServer:
        default: api-develop.silohub.net
        description: Nombre de dominio del api server SILOHUB
        enum:
          - api-develop.silohub.net
      #          - mock-api-develop.silohub.net
tags:
  - name: server-info
    description: Server Runtime Information
  - name: accounts
    description: Account Information
paths:
  /api/retailers/v0/{retailerCode}/server-info:
    $ref: paths/serverInfo/serverInfo.yaml
  /api/retailers/v0/{retailerCode}/accounts/{accountId}/movements:
    $ref: paths/retailers/accounts/SearchMovements.yaml
components:
  securitySchemes:
    OAuth2:
      $ref: components/securitySchemes/OAuth2.yaml
