openapi: 3.0.3
info:
  title: "Retailer Application Backend"
  description: |
    Esta API es el "Back for Front" (BFF) de la aplicación "SILOHUB Retailer".
    Provee los servicios para la aplicación de usuario (Web, Android, iOS).
  version: "0.0"
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  contact:
    name: SILOHUB Support
    email: support@silohub.ag
    url: 'https://silohub.atlassian.net/servicedesk/customer/portals'
externalDocs:
  description: Confluence
  url: 'https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs'
servers:
  - url: 'https://{apiServer}/bff/retailers/v0/{retailerCode}'
    variables:
      apiServer:
        default: api-develop.silohub.net
        description: Nombre de dominio del api server SILOHUB
        enum:
          - api-develop.silohub.net
#          - mock-api-develop.silohub.net
      retailerCode:
        default: silohub
        enum:
          - silohub
#          - redpil
#          - bluepill
        description: Código del retailer al que representa el BFF
tags:
  - name: user-info
    description: User Information
paths:
  /user-info:
    $ref: paths/userInfo/userInfo.yaml
  /user-permissions:
    $ref: paths/userPermissions/userPermissions.yaml
components:
  securitySchemes:
    OAuth2:
      $ref: components/securitySchemes/OAuth2.yaml