openapi: 3.0.3
info:
  title: "Retailer Application Backend"
  description: |
    Esta API es el "Back for Front" (BFF) de la aplicación "SILOHUB Retailer".
    Provee los servicios para la aplicación de usuario (Web, Android, iOS).
  version: "0.0"
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  contact:
    name: SILOHUB Support
    email: support@silohub.ag
    url: 'https://silohub.atlassian.net/servicedesk/customer/portals'
externalDocs:
  description: Confluence
  url: 'https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs'
servers:
  - url: 'https://{apiServer}/bff/retailers/{retailerCode}'
    variables:
      apiServer:
        default: api-develop.silohub.net
        description: Nombre de dominio del api server SILOHUB
      retailerCode:
        default: silouhb
        description: Código del retailer al que representa el BFF
tags:
  - name: server-info
    description: Server Runtime Information
paths:
  /server-info:
    $ref: paths/serverInfo/serverInfo.yaml
