openapi: 3.0.3
info:
  title: "BFF User Information"
  description: |
    Esta API es parte del "Back for Front" (BFF) de las aplicaciones Front.
    Provee los servicios para la aplicación de usuario (Web, Android, iOS).
  version: "0.0"
  x-group: "BFF-Retailer"
  x-client-id: "bff-retailer"
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  contact:
    name: SILOHUB Support
    email: support@silohub.ag
    url: 'https://silohub.atlassian.net/servicedesk/customer/portals'
externalDocs:
  description: Confluence
  url: 'https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs'
servers:
  - url: 'https://{apiServer}'
    variables:
      apiServer:
        default: api-develop.silohub.net
        description: Nombre de dominio del api server SILOHUB
        enum:
          - api-develop.silohub.net
#          - mock-api-develop.silohub.net
tags:
  - name: user-info
    description: Información de usuarios
paths:
  /bff/retailers/v0/{retailerCode}/user-info:
    $ref: paths/retailers/core/UserInfo.yaml
  /bff/retailers/v0/{retailerCode}/user-permissions:
    $ref: paths/retailers/core/UserPermissions.yaml
components:
  securitySchemes:
    OAuth2:
      $ref: components/securitySchemes/OAuth2.yaml
