openapi: 3.0.2
info:
  title: SILOHUB Core API
  description: Core entities of the product
  version: develop
  license:
    name: Privada
    url: https://www.silohub.ag
  contact:
    name: SILOHUB Support
    email: support@silohub.ag
    url: 'https://silohub.atlassian.net/servicedesk/customer/portals'
  x-logo:
    url: https://www.silohub.ag/wp-content/uploads/2021/09/signature-logo.png
    altText: SILOHUB Logo
externalDocs:
  description: Confluence
  url: 'https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs'
servers:
  - url: 'https://api.server.test/v1'
paths:
  /companies:
    $ref: paths/companies.yaml
  /companies/{companyId}:
    $ref: "paths/companies/{companyId}.yaml"
tags:
  - name: core
    description: Métodos de uso base
  - name: masterdata
    description: Datos de base
components:
  securitySchemes:
    oauth:
      $ref: components/securitySchemes/oauth.yaml