openapi: 3.0.2
info:
  title: SILOHUB Core API
  description: Core entities of the product
  version: develop
  license:
    name: Privada
    url: https://www.silohub.ag
  contact:
    name: SILOHUB Support
    email: support@silohub.ag
    url: 'https://silohub.atlassian.net/servicedesk/customer/portals'
  x-logo:
    url: https://www.silohub.ag/wp-content/uploads/2021/09/signature-logo.png
    altText: SILOHUB Logo
externalDocs:
  description: Confluence
  url: 'https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs'
servers:
  - url: 'https://api-develop.silohub.net'
    description: Develop Server
paths:
  /companies:
    $ref: paths/companies.yaml
  /companies/{companyId}:
    $ref: paths/companies/{companyId}.yaml
  /companies/byUniqueReference:
    $ref: paths/companies/byUniqueReference.yaml
  /companies/{refType}/{refValue}:
    $ref: paths/companies/{refType}-{refValue}.yaml
tags:
  - name: companies
    description: Companies Data
components:
  securitySchemes:
    oauth:
      $ref: components/securitySchemes/oauth.yaml