openapi: 3.0.3
info:
  contact:
    email: support@silohub.ag
    name: SILOHUB Support
    url: https://silohub.atlassian.net/servicedesk/customer/portals
  description: |
    Esta API es parte del "Back for Front" (BFF) de las aplicaciones Front.
    Provee los servicios para la aplicación de usuario (Web, Android, iOS).
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  title: BFF User Information
  version: 0.0.101
  x-group: BFF-Retailer
  x-client-id: bff-retailer
externalDocs:
  description: Confluence
  url: https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs
servers:
- url: https://{apiServer}/bff/retailers/v0/{retailerCode}
  variables:
    apiServer:
      default: api-develop.silohub.net
      description: Nombre de dominio del api server SILOHUB
      enum:
      - api-develop.silohub.net
    retailerCode:
      default: silohub
      description: Código del retailer al que representa el BFF
      enum:
      - silohub
tags:
- description: User Information
  name: user-info
paths:
  /user-info:
    get:
      operationId: getUserInfo
      responses:
        "200":
          content:
            application/json:
              examples:
                bffRetailer:
                  $ref: '#/components/examples/User1'
              schema:
                $ref: '#/components/schemas/User'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Show User Information
      tags:
      - user-info
  /user-permissions:
    get:
      operationId: getBffUserPermissions
      responses:
        "200":
          content:
            application/json:
              examples:
                bffRetailer:
                  $ref: '#/components/examples/User1Permissions'
              schema:
                $ref: '#/components/schemas/UserPermissions'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Get User Permissions for BFF
      tags:
      - user-info
components:
  examples:
    User1:
      summary: User 1
      value:
        userId: 74327988-2c24-4931-8547-2a870d86c044
        displayName: User 1 example
        language: es_AR
        timezone: America/Argentina/Cordoba
        uniqueReferences:
        - refType: DNI
          refValue: "33444555"
        references:
        - refType: SITUACION
          refValue: Pendiente
        notes: |
          This is a sample note.
          You should be able to store long values here.
        created: 2021-09-10T12:32:28Z
        updated: 2021-10-10T12:32:28Z
    User1Permissions:
      summary: User 1 Permissions
      value:
        permissions:
        - path: /hub/home
          actions:
          - '*'
        - path: /hub/grain/*
          actions:
          - '*'
        - path: /*
          actions:
          - read
          - write
  schemas:
    User:
      description: |
        Un usuario del sistema
      properties:
        userId:
          $ref: '#/components/schemas/Uuid'
        displayName:
          description: User Display Name
          type: string
        language:
          description: User Language / Locale
          type: string
        timezone:
          description: User Timezone
          type: string
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
        notes:
          $ref: '#/components/schemas/Notes'
        created:
          $ref: '#/components/schemas/AuditDate'
        updated:
          $ref: '#/components/schemas/AuditDate'
      required:
      - created
      - displayName
      - updated
      - userId
      type: object
    UserPermissions:
      description: Permissions
      properties:
        permissions:
          items:
            $ref: '#/components/schemas/UserPermissions_permissions'
          type: array
      required:
      - permissions
      type: object
    Uuid:
      description: |
        [Identificador único universal](https://es.wikipedia.org/wiki/Identificador_%C3%BAnico_universal) (UUID)
      format: uuid
      readOnly: true
      type: string
    UniqueReferences:
      description: Pares de clave-valor, que son únicas entre distintas entidades
      example:
        key1: value1
        key2: value2
      items:
        $ref: '#/components/schemas/Reference'
      type: array
    References:
      description: Pares de clave-valor, que se pueden repetir entre distintas entidades
      example:
        key1: value1
        key2: value2
      items:
        $ref: '#/components/schemas/Reference'
      type: array
    Notes:
      description: |
        Notas adicionales
      maxLength: 5000
      type: string
    AuditDate:
      description: |
        [Marca temporal](https://es.wikipedia.org/wiki/Marca_temporal) (Timestamp)
      format: date-time
      readOnly: true
      type: string
    Reference:
      description: |
        Referencia externa de la entidad.

        Siempre consiste en un tipo de referencia y el valor de la ella.
      properties:
        refType:
          $ref: '#/components/schemas/RefType'
        refKey:
          $ref: '#/components/schemas/RefKey'
        refValue:
          $ref: '#/components/schemas/RefValue'
      required:
      - refKey
      - refType
      - refValue
      type: object
    RefType:
      description: |
        Tipo de referencia. Por ejemplo CUIT
      example: CUIT
      pattern: ^[A-Z\-]+$
      type: string
    RefKey:
      description: |
        Clave de referencia. Por ejemplo Empresa Algoritmo
      example: ALG
      pattern: ^[A-Z\-]+$
      type: string
    RefValue:
      description: |
        Valor de la referencia. Por ejemplo el número de CUIT
      example: "30224445556"
      pattern: ^[A-Za-z0-9\-_]+$
      type: string
    UserPermissions_permissions:
      properties:
        path:
          type: string
        actions:
          items:
            type: string
          type: array
      type: object
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://iam-develop.silohub.net/auth/realms/SILOHUB/protocol/openid-connect/token
      type: oauth2
