openapi: 3.0.3
info:
  contact:
    email: support@silohub.ag
    name: SILOHUB Support
    url: https://silohub.atlassian.net/servicedesk/customer/portals
  description: |
    Esta API es el "Back for Front" (BFF) de la aplicación "SILOHUB Retailer".
    Provee los servicios para la aplicación de usuario (Web, Android, iOS).
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  title: BFF for Retailer
  version: 0.0.104
  x-group: BFF-Retailer
  x-client-id: bff-retailer
externalDocs:
  description: Confluence
  url: https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs
servers:
- url: https://{apiServer}
  variables:
    apiServer:
      default: api-develop.silohub.net
      description: Nombre de dominio del api server SILOHUB
      enum:
      - api-develop.silohub.net
tags:
- description: Server Runtime Information
  name: server-info
- description: Account Information
  name: accounts
- description: Información de países
  name: countries
- description: Información de monedas
  name: currencies
paths:
  /bff/retailers/v0/{retailerCode}/server-info:
    get:
      operationId: getServerInfo
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              examples:
                bffRetailer:
                  $ref: '#/components/examples/BffRetailer'
              schema:
                $ref: '#/components/schemas/ServerInfo'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      summary: Show Server Runtime Information
      tags:
      - server-info
  /bff/retailers/v0/{retailerCode}/accounts/{accountId}/movements:
    post:
      operationId: searchRetailerAccountsMovements
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Account Id
        in: path
        name: accountId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Search'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchMovementsResult'
          description: The response contains the search result
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: List Account Movements
      tags:
      - accounts
  /bff/retailers/v0/{retailerCode}/countries:
    post:
      operationId: searchRetailerCountries
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Search'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCountriesResult'
          description: The response contains the search result
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Listar los países
      tags:
      - countries
  /bff/retailers/v0/{retailerCode}/currencies:
    post:
      operationId: searchRetailerCurrencies
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Search'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCurrenciesResult'
          description: The response contains the search result
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Listar las monedas
      tags:
      - currencies
components:
  examples:
    BffRetailer:
      summary: BFF Retailer
      value:
        version: 1.0.1234-develop
        versionShort: 1.0
        runtimeEnvironment: test
  schemas:
    ServerInfo:
      description: |
        La información del server que nos estamos conectando
      properties:
        version:
          description: Versión completa del runtime
          type: string
        versionShort:
          description: Versión corta (major.mino) del runtime
          type: string
        runtimeEnvironment:
          description: Entorno del runtime
          type: string
      required:
      - runtimeEnvironment
      - version
      - versionShort
      type: object
    Search:
      description: Search parameters
      properties:
        queryId:
          type: string
        from:
          type: integer
        to:
          type: integer
        maxRows:
          type: integer
        filters:
          items:
            type: string
          type: array
      required:
      - from
      - maxRows
      - to
      type: object
    SearchMovementsResult:
      description: Collection of users
      properties:
        queryId:
          type: string
        totalRows:
          type: integer
        rows:
          $ref: '#/components/schemas/ArrayOfMovement'
      type: object
    SearchCountriesResult:
      description: Lista de países
      properties:
        queryId:
          type: string
        totalRows:
          type: integer
        rows:
          $ref: '#/components/schemas/ArrayOfCountry'
      type: object
    SearchCurrenciesResult:
      description: List de monedas
      properties:
        queryId:
          type: string
        totalRows:
          type: integer
        rows:
          $ref: '#/components/schemas/ArrayOfCurrency'
      type: object
    ArrayOfMovement:
      description: List of movements
      items:
        $ref: '#/components/schemas/Movement'
      type: array
    ArrayOfCountry:
      description: Lista de países
      example:
        $ref: ../../examples/countries/ArrayOfCountry.yaml
      items:
        $ref: '#/components/schemas/Country'
      type: array
    ArrayOfCurrency:
      description: Lista de monedas
      example:
        $ref: ../../examples/currencies/ArrayOfCurrency.yaml
      items:
        $ref: '#/components/schemas/Currency'
      type: array
    Movement:
      description: |
        La información del server que nos estamos conectando
      properties:
        version:
          description: Versión completa del runtime
          type: string
        versionShort:
          description: Versión corta (major.mino) del runtime
          type: string
        runtimeEnvironment:
          description: Entorno del runtime
          type: string
        money:
          description: Entorno del runtime
          format: double
          type: number
        versionNumber:
          description: Entorno del runtime
          type: integer
        versionDate:
          description: Entorno del runtime
          format: date
          type: string
        versionCreate:
          description: Entorno del runtime
          format: date-time
          type: string
        versionActive:
          description: Entorno del runtime
          type: boolean
      required:
      - runtimeEnvironment
      - version
      - versionShort
      type: object
    Country:
      description: |
        Un país definido por la ISO
      properties:
        countryCode:
          $ref: '#/components/schemas/CountryCode'
        countryAlpha3Code:
          $ref: '#/components/schemas/CountryAlpha3Code'
        countryNumericCode:
          description: Country numeric code
          type: integer
        name:
          description: Country Name
          type: string
        currencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        active:
          description: Is Active
          type: boolean
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
        notes:
          $ref: '#/components/schemas/Notes'
        created:
          $ref: '#/components/schemas/AuditDate'
        updated:
          $ref: '#/components/schemas/AuditDate'
      required:
      - active
      - countryAlpha3Code
      - countryCode
      - countryNumericCode
      - created
      - currencyCode
      - name
      - updated
      type: object
    Currency:
      description: |
        Una moneda definida por la ISO
      properties:
        currencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        currencyNumericCode:
          description: Currency numeric code
          type: integer
        decimals:
          description: Decimals in the currency
          type: integer
        name:
          description: Currency Name
          type: string
        active:
          description: Is Active
          type: boolean
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
        created:
          $ref: '#/components/schemas/AuditDate'
        updated:
          $ref: '#/components/schemas/AuditDate'
      required:
      - active
      - created
      - currencyCode
      - currencyNumericCode
      - decimals
      - name
      - updated
      type: object
    CountryCode:
      description: |
        Identificador de país según [ISO 3166-1 alpha-2](https://es.wikipedia.org/wiki/ISO_3166-1)
      example: '[AR, BR, CL, UY, US]'
      maxLength: 2
      minLength: 2
      type: string
    CountryAlpha3Code:
      description: |
        Identificador de país según [ISO 3166-1 alpha-3](https://es.wikipedia.org/wiki/ISO_3166-1)
      example: '[ARG, BRA, CHL, URY, USA]'
      maxLength: 3
      minLength: 3
      type: string
    CurrencyCode:
      description: '[ISO 4217 Code](https://es.wikipedia.org/wiki/ISO_4217)'
      example: '[ARS, USD, BRL, CNY]'
      maxLength: 3
      minLength: 3
      type: string
    UniqueReferences:
      description: Pares de clave-valor, que son únicas entre distintas entidades
      example:
        key1: value1
        key2: value2
      items:
        $ref: '#/components/schemas/Reference'
      type: array
    References:
      description: Pares de clave-valor, que se pueden repetir entre distintas entidades
      example:
        key1: value1
        key2: value2
      items:
        $ref: '#/components/schemas/Reference'
      type: array
    Notes:
      description: |
        Notas adicionales
      maxLength: 5000
      type: string
    AuditDate:
      description: |
        [Marca temporal](https://es.wikipedia.org/wiki/Marca_temporal) (Timestamp)
      format: date-time
      readOnly: true
      type: string
    Reference:
      description: |
        Referencia externa de la entidad.

        Siempre consiste en un tipo de referencia y el valor de la ella.
      properties:
        refType:
          $ref: '#/components/schemas/RefType'
        refKey:
          $ref: '#/components/schemas/RefKey'
        refValue:
          $ref: '#/components/schemas/RefValue'
      required:
      - refKey
      - refType
      - refValue
      type: object
    RefType:
      description: |
        Tipo de referencia. Por ejemplo CUIT
      example: CUIT
      pattern: ^[A-Z\-]+$
      type: string
    RefKey:
      description: |
        Clave de referencia. Por ejemplo Empresa Algoritmo
      example: ALG
      pattern: ^[A-Z\-]+$
      type: string
    RefValue:
      description: |
        Valor de la referencia. Por ejemplo el número de CUIT
      example: "30224445556"
      pattern: ^[A-Za-z0-9\-_]+$
      type: string
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://iam-develop.silohub.net/auth/realms/SILOHUB/protocol/openid-connect/token
      type: oauth2
