openapi: 3.0.3
info:
  contact:
    email: support@silohub.ag
    name: SILOHUB Support
    url: https://silohub.atlassian.net/servicedesk/customer/portals
  description: |
    Esta API es el core de negocio del retailer para SILOHUB
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  title: SILOHUB Retailer API
  version: 0.0.104
  x-group: API
  x-client-id: api-client-retailer
externalDocs:
  description: Confluence
  url: https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs
servers:
- url: https://{apiServer}
  variables:
    apiServer:
      default: api-develop.silohub.net
      description: Nombre de dominio del api server SILOHUB
      enum:
      - api-develop.silohub.net
tags:
- description: Server Runtime Information
  name: server-info
- description: Account Information
  name: accounts
paths:
  /api/retailers/v0/{retailerCode}/server-info:
    get:
      operationId: getServerInfo
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              examples:
                bffRetailer:
                  $ref: '#/components/examples/BffRetailer'
              schema:
                $ref: '#/components/schemas/ServerInfo'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      summary: Show Server Runtime Information
      tags:
      - server-info
  /api/retailers/v0/{retailerCode}/accounts/{accountId}/movements:
    post:
      operationId: searchRetailerAccountsMovements
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Account Id
        in: path
        name: accountId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Search'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchMovementsResult'
          description: The response contains the search result
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: List Account Movements
      tags:
      - accounts
components:
  examples:
    BffRetailer:
      summary: BFF Retailer
      value:
        version: 1.0.1234-develop
        versionShort: 1.0
        runtimeEnvironment: test
  schemas:
    ServerInfo:
      description: |
        La información del server que nos estamos conectando
      properties:
        version:
          description: Versión completa del runtime
          type: string
        versionShort:
          description: Versión corta (major.mino) del runtime
          type: string
        runtimeEnvironment:
          description: Entorno del runtime
          type: string
      required:
      - runtimeEnvironment
      - version
      - versionShort
      type: object
    Search:
      description: Search parameters
      properties:
        queryId:
          type: string
        from:
          type: integer
        to:
          type: integer
        maxRows:
          type: integer
        filters:
          items:
            type: string
          type: array
      required:
      - from
      - maxRows
      - to
      type: object
    SearchMovementsResult:
      description: Collection of users
      properties:
        queryId:
          type: string
        totalRows:
          type: integer
        rows:
          $ref: '#/components/schemas/ArrayOfMovement'
      type: object
    ArrayOfMovement:
      description: List of movements
      items:
        $ref: '#/components/schemas/Movement'
      type: array
    Movement:
      description: |
        La información del server que nos estamos conectando
      properties:
        version:
          description: Versión completa del runtime
          type: string
        versionShort:
          description: Versión corta (major.mino) del runtime
          type: string
        runtimeEnvironment:
          description: Entorno del runtime
          type: string
        money:
          description: Entorno del runtime
          format: double
          type: number
        versionNumber:
          description: Entorno del runtime
          type: integer
        versionDate:
          description: Entorno del runtime
          format: date
          type: string
        versionCreate:
          description: Entorno del runtime
          format: date-time
          type: string
        versionActive:
          description: Entorno del runtime
          type: boolean
      required:
      - runtimeEnvironment
      - version
      - versionShort
      type: object
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://iam-develop.silohub.net/auth/realms/SILOHUB/protocol/openid-connect/token
      type: oauth2
